export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const ACTIVE_ACCOUNT_ERROR = "ACTIVE_ACCOUNT_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ISAUTHENTICATE = "ISAUTHENTICATE";

export const GETALLUSER = "GETALLUSER";
export const GETALLUSER_ERROR = "GETALLUSER_ERROR";

export const FIND_MAIL = "FIND_MAIL";
export const FIND_MAIL_ERROR = "FIND_MAIL_ERROR";

export const RECOVER_PASS = "RECOVER_PASS";
export const RECOVER_PASS_ERROR = "RECOVER_PASS_ERROR";

export const FRESH_USER = "FRESH_USER";
