export const REGISTER_ADMIN = "REGISTER_ADMIN";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const LOGIN_ADMIN = "LOGIN_ADMIN";
export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";

export const ACTIVE_ACCOUNT_ADMIN = "ACTIVE_ACCOUNT_ADMIN";
export const ACTIVE_ACCOUNT_ADMIN_ERROR = "ACTIVE_ACCOUNT_ADMIN_ERROR";

export const LOGOUT_ADMIN = "LOGOUT_ADMIN";

export const ISAUTHENTICATE_ADMIN = "ISAUTHENTICATE_ADMIN";

export const GETALLUSER = "GETALLUSER";
export const GETALLUSER_ERROR = "GETALLUSER_ERROR";

export const FIND_MAIL_ADMIN = "FIND_MAIL_ADMIN";
export const FIND_MAIL_ADMIN_ERROR = "FIND_MAIL_ADMIN_ERROR";

export const RECOVER_PASS_ADMIN = "RECOVER_PASS_ADMIN";
export const RECOVER_PASS_ADMIN_ERROR = "RECOVER_PASS_ADMIN_ERROR";

export const APPROVED = "APPROVED";
export const APPROVED_ERROR = "APPROVED_ERROR";

export const DELETE_JUDGE = "DELETE_JUDGE";
export const DELETE_JUDGE_ERROR = "DELETE_JUDGE_ERROR";

export const FRESH_USER = "FRESH_USER";
