export const POST_ARTICLE = "POST_ARTICLE";
export const POST_ARTICLE_ERROR = "POST_ARTICLE_ERROR";

export const GET_MY_ARTICLE = "GET_MY_ARTICLE";
export const GET_MYARTICLE_ERROR = "GET_MYARTICLE_ERROR";

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";

export const GET_INDIVIDUAL_ARTICLES = "GET_INDIVIDUAL_ARTICLES";
export const GET_INDIVIDUAL_ARTICLES_ERROR = "GET_INDIVIDUAL_ARTICLES_ERROR";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";
export const UPDATE_ARTICLE_ERROR = "UPDATE_ARTICLE_ERROR";

export const DELETE_ARTICLES = "DELETE_ARTICLES";
export const DELETE_ARTICLES_ERROR = "DELETE_ARTICLES_ERROR";

export const MODAL_TOGGLE = "MODAL_TOGGLE";

export const ENABLE_BTN = "ENABLE_BTN";