export const QUARTERLYANNOUCE = "QUARTERLYANNOUCE";
export const QUARTERLYANNOUCE_ERROR = "QUARTERLYANNOUCE_ERROR";

export const UPDATE_QUARTERLYANNOUCE = "UPDATE_QUARTERLYANNOUCE";
export const UPDATE_QUARTERLYANNOUCE_ERROR = "UPDATE_QUARTERLYANNOUCE_ERROR";

export const GET_QUARTERLYANNOUCE = "GET_QUARTERLYANNOUCE";
export const GET_QUARTERLYANNOUCE_ERROR = "GET_QUARTERLYANNOUCE_ERROR";
