export const POST_ARTICLE = "POST_ARTICLE";
export const POST_ARTICLE_ERROR = "POST_ARTICLE_ERROR";

export const GET_MY_ARTICLE = "GET_MY_ARTICLE";
export const GET_MYARTICLE_ERROR = "GET_MYARTICLE_ERROR";
